import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils"
import QueryProvider from "@/QueryProvider";
import "@/http"
import AuthContext from "@/Context/AuthContext";
import { Toaster } from "@/components/ui/sonner"
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <QueryProvider>
          <AuthContext>
            {children}
            <Toaster expand closeButton/>
          </AuthContext>
        </QueryProvider>
      </body>
    </html>
  );
}
